// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahcuG0YmoBzDOQs_-u2RtqYrb1NxUffI',
    appId: '1:825414188661:web:95ac6c005d9a4a8c34823c',
    messagingSenderId: '825414188661',
    projectId: 'latihan-auth-sanberapp-53c61',
    authDomain: 'latihan-auth-sanberapp-53c61.firebaseapp.com',
    storageBucket: 'latihan-auth-sanberapp-53c61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd6Y1kevwbDBXiHiCLdsTCA9xDcjMLkn0',
    appId: '1:825414188661:android:152c1076de987ae534823c',
    messagingSenderId: '825414188661',
    projectId: 'latihan-auth-sanberapp-53c61',
    storageBucket: 'latihan-auth-sanberapp-53c61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGfFwlcKV52doMGmojxjSXKT-BBs8B33o',
    appId: '1:825414188661:ios:3a1d8060965c41a634823c',
    messagingSenderId: '825414188661',
    projectId: 'latihan-auth-sanberapp-53c61',
    storageBucket: 'latihan-auth-sanberapp-53c61.appspot.com',
    iosBundleId: 'com.example.sanberappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGfFwlcKV52doMGmojxjSXKT-BBs8B33o',
    appId: '1:825414188661:ios:a495075ccee9824734823c',
    messagingSenderId: '825414188661',
    projectId: 'latihan-auth-sanberapp-53c61',
    storageBucket: 'latihan-auth-sanberapp-53c61.appspot.com',
    iosBundleId: 'com.example.sanberappflutter.RunnerTests',
  );
}
